# Generated by Django 2.1 on 2019-01-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoModel',
        ),
    ]
