# Generated by Django 2.1 on 2018-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensourcecourses',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
